ALTER TABLE IF EXISTS department
  DROP COLUMN manager;

DROP TABLE IF EXISTS employee_project;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS department;

CREATE TABLE project (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  project_name TEXT NOT NULL,
  budget NUMERIC DEFAULT 0,
  start_date DATE
);

CREATE TABLE department (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  department_name TEXT NOT NULL
);

CREATE TABLE employee (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  employee_name TEXT NOT NULL,
  phone TEXT,
  title TEXT,
  salary NUMERIC,
  department_id INT REFERENCES department(id)
);

ALTER TABLE department
  ADD COLUMN manager_id INT REFERENCES employee(id);

CREATE TABLE employee_project (
  employee_id INT REFERENCES employee(id),
  project_id INT REFERENCES project(id),
  start_date DATE,
  end_date DATE,
  PRIMARY KEY (employee_id, project_id)
)
