
drop type if exists grocery;
create type grocery as enum(
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);

create table if not exists shopping_list(
  id int primary key generated by default as identity,
  name char(50) not null,
  price decimal(8,2),
  date_added timestamp default now(),
  checked boolean default false,
  category grocery not null
);
